ilyaSy/react-bbbs

.eslintrc.json
package-lock.json
src/components/Button/button.css
src/components/Calendar/Calendar.js
src/components/CalendarCard/CalendarCard.js
src/components/Content/Content.js
src/components/Content/content.css
src/components/WhereToGo/WhereToGo.css
src/components/WhereToGo/WhereToGo.js
src/utils/serverApiTestConfig.js

Добавил новый конфиг в линт, чтоб работал аксиос
Добавил обертки в контент
Создал страницу куда пойти
календарю задал пропсы из апи
!!!! Подключил библиотеку date-fns -  https://date-fns.org/v2.21.3/docs/startOfHour

Where to go

---

src/components/App/App.js
src/components/Button/Button.js
src/components/Button/button.css
src/components/CalendarCard/CalendarCard.js
src/components/MainPage/MainPage.js
src/components/Movie/Movie.js
src/components/MoviesContainer/MoviesContainer.js
src/components/PopupConfirmRegister/PopupConfirmRegister.js
src/components/PopupMeet/PopupMeet.js
src/components/PopupRegisterSuccess/PopupRegisterSuccess.js
src/components/ProtectedRoute/ProtectedRoute.js
src/components/QuestionsContainer/QuestionsContainer.js
src/utils/format.js

Пофиксил некоторые ошибки в консоли, и немножко доработал попапы

fix popups and errors

---

.eslintrc.json
package-lock.json
package.json
src/components/App/App.js
src/components/AuthPopup/AuthPopup.js

!! Подключил библиотеку реакт-форм
!! Добавил правилу линтеру чтобы пропускал спреды
Сделал авторизацию с помощью реакт-форм
Сделал простенькую валидацию
Чуть чуть изменил логику попапов календаря по ТЗ
___
Нет стилей для инпутов-еррор и неактивной кнопки - нужно сделать

login validation 

---

src/components/CalendarCardProfile/CalendarCardProfile.js
src/components/CalendarCardProfile/calendarCardProfile.css
src/components/Content/Content.js
src/components/PersonalAccount/PersonalAccount.js

в профиле показаны и открываются события на которые ты регестрировался

профиль хедер реди

---

public/index.html
src/components/CreatePlace/CreatePlace.js
src/components/Popup/popup.css
src/components/PopupPlaces/PopupPlaces.js

Заготовка для обработки сабмита формы, которая позволяет добавить новое место посещения.
Пока только выводит в консоль объект с данными. 
+ Поменяла язык и заголовок страницы
+ Добавила пробелы там, где их не хватало (тире не отрывалось от текста).

Feat: form submit handling (places)

---

src/components/PersonalAccount/PersonalAccount.js
src/components/PopupCities/PopupCities.css
src/components/PopupCities/PopupCities.js

Добавлено окошко с выбором городом на личную страницу. 
Нужно будет поменять просто списки, на кнопки.

add popup with cities in personalAccount

---

src/components/CalendarCard/CalendarCard.js
src/components/PersonalAccount/PersonalAccount.js
src/components/PopupStoryFriendship/PopupStoryFriendship.js

немножко изменил карточку в профиле

Calendar filter

---

src/components/Calendar/Calendar.js
src/components/Content/Content.js
src/components/MainPage/MainPage.js
src/components/PersonalAccount/PersonalAccount.js
src/components/Place/Place.css
src/components/ProtectedRoute/ProtectedRoute.js
src/components/WhereToGo/WhereToGo.js

Нужно будет добавить классы в Куда пойти в соответствии с исправлениями команды вёрстки.
Прошу это сделать Аню, так как она занимается этой страницей.

Добавила все стили в соответствии с версткой

---

src/components/CalendarCard/CalendarCard.js
src/utils/serverApi.js

фис карточки календаря ( места + дизейбл )

fix calendar places

---

src/components/App/App.js
src/components/AuthPopup/AuthPopup.js
src/components/CalendarCard/CalendarCard.js
src/components/Content/Content.js
src/components/Header/Header.js
src/components/Header/header.css
src/components/PersonalAccount/PersonalAccount.js
src/components/PersonalAccountCardStory/PersonalAccountCardStory.js
src/components/Popup/Popup.js
src/components/Popup/popup.css
src/components/PopupConfirmRegister/PopupConfirmRegister.js
src/components/PopupMeet/PopupMeet.js
src/components/PopupPlaces/PopupPlaces.js
src/components/PopupRegisterSuccess/PopupRegisterSuccess.js
src/components/Search/Search.js
src/components/Search/search.css

добавил разметку поиска ( надо чуток править верстку и настраивать функционал )
Отрефакторил отрисовку попапов
пофиксил календарь

add search and refacroting popups and calendar

---

src/components/App/App.js
src/components/Content/Content.js
src/components/PersonalAccount/PersonalAccount.js
src/components/PopupCities/PopupCities.js
src/components/ProtectedRoute/ProtectedRoute.js
src/components/Question/Question.js
src/components/WhereToGo/WhereToGo.js
src/utils/serverApi.js
src/utils/serverApiTestConfig.js

Настроил попап с городами. Осталось добавить фильтр =)
что то намутил, Ошибочка в консоли есть ( при переходе в куда пойти ) , но она не мешает работе сайта. Исправьте кто шарит)

add popup cities

---

src/components/App/App.js
src/components/Content/Content.js
src/components/CreatePlace/CreatePlace.css
src/components/CreatePlace/CreatePlace.js
src/components/Header/Header.js
src/components/PageNotFound/PageNotFound.js
src/components/PopupPlaces/PopupPlaces.css
src/components/PopupPlaces/PopupPlaces.js
src/components/WhereToGo/WhereToGo.css
src/components/WhereToGo/WhereToGo.js

добавил изменить город в куда пойти
поправил верстку попапа в "Куда пойти" и анимировал.
P.S. сравнивайте с макетом верстку, я замучался ее переделывать.
И нужно адаптив еще поправить

fix cities

---

src/components/Place/Place.css
src/components/Place/Place.js
src/components/WhereToGo/WhereToGo.js
src/utils/colorRender.js
src/utils/serverApiTestConfig.js

Добавлена функция для определения цвета карточки (по тз есть определённый порядок). 
+ пропсы для карточек мест

feat: rendering card colors in given order

---

src/components/BooksPage/BooksPage.js
src/components/Button/button.css
src/components/Content/Content.js
src/components/MoviesPage/MoviesPage.js
src/components/VideosPage/VideosPage.css
src/components/VideosPage/VideosPage.js
src/utils/serverApiTestConfig.js

Добавлена страница Видео:
* рендеринг компонента + стили
* пагинация (доработать, жмутся пустые страницы)
* фильтр-рубрикатор (! условие тз: только авторизованный юзер видит видео "Ресурсная группа")
* обновлены данные (теги-рубрики, выбор модератора)
+ небольшие исправления (комменты, названия классов, параметров и пр)

Feat: videos page + minor fixes (naming)

---

src/components/ArticleGuide/ArticleGuide.css
src/components/Content/Content.js
src/components/GuidePage/GuidePage.css
src/components/GuidePage/GuidePage.js

Добавлена страница Справочник
!!! нет линий между рядами; то, как это реализовано в вёрстке, применить не получилось пока, надо подумать

feat: guide page (correct row lines styles needed)

---

src/components/Cards/StoryCard/StoryCard.css
src/components/Cards/StoryCard/StoryCard.js

Добавлено затемнение истории при наведении мыши на десктопах (1240px и выше)

Затемнение истории на главной

---

src/components/App/App.js
src/components/Modals/PopupError/PopupError.js
src/components/Modals/PopupError/popupError.css

попап с ошибкой при регистрации в ивенте

err popup done

---

src/components/App/App.js
src/components/Containers/Navigation/Navigation.css
src/components/Containers/Navigation/Navigation.js
src/components/Header/Header.js
src/components/Header/header.css

Добавлены новые стили для кнопок "Изменить город" и "Выход" в Navigation.css. Изменены стили и сам компонент Header, так как бургер добавляется в нём.

Переделан бургер для разрешений 1024 и меньше

---

src/components/Containers/Navigation/Navigation.css
src/components/Containers/Navigation/Navigation.js
src/components/UI/Button/button.css

Убрано отображение скролла для Firefox.
Улучшено отображение кнопок город/выход в бургере.

Скрыт скролл + выравнивание кнопок в бургере

---

src/blocks/readwatch.css
src/components/App/App.js
src/components/Cards/Card/Card.css
src/components/Cards/VideoCard/VideoCard.css
src/components/Cards/VideoCard/VideoCard.js
src/components/Containers/ReadAndWatchSection/ReadAndWatchSection.js
src/components/Content/Content.js
src/components/Modals/YoutubeEmbed/YoutubeEmbed.js
src/components/Pages/MoviesPage/MoviesPage.js
src/components/Pages/ReadAndWatch/ReadAndWatch.css
src/components/Pages/ReadAndWatch/ReadAndWatch.js

Добавил и настроил попап для видео
Добавил регулярное выражение для парсинга ютуб-ссылки в Embed-id формат
Сделал превьюшки для видео
+ мелкие фиксы цсс

фиксы цсс,  видео, попап

---

src/components/Cards/ArticleCard/ArticleCard.js
src/components/Cards/MainVideoCard/MainVideoCard.js
src/components/Pages/About/About.js
src/components/Pages/PersonalAccount/PersonalAccount.css
src/components/Pages/PersonalAccount/PersonalAccount.js

Добавлены пару ссылок на карточки на главной странице
Исправлено пару опечаток
Поправлен значок добавления фото в добавлении истории

Ссылки + опечатки

---

src/components/Containers/Navigation/Navigation.js
src/components/Modals/MenuReadWatch/MenuReadWatch.css
src/components/Modals/MenuReadWatch/MenuReadWatch.js

Добавлено выпадающее меню для кнопки "читать смотреть" в шапке сайта. Работает только на больших разрешениях, пока меню не "прячется" в бургер.

Выпадающее меню для "Читать и смотреть"

---

src/components/App/App.js
src/components/Cards/MainVideoCard/MainVideoCard.css
src/components/Cards/MainVideoCard/MainVideoCard.js
src/components/Cards/PersonalAccountCardStory/PersonalAccountCardStory.js
src/components/Cards/QuestionCard/QuestionCard.css
src/components/Cards/Search/Search.js
src/components/Cards/VideoCard/VideoCard.js
src/components/Containers/MoviesContainer/MoviesContainer.js
src/components/Content/Content.js
src/components/Header/Header.js
src/components/Modals/MenuReadWatch/MenuReadWatch.js
src/components/Modals/PopupStoryFriendship/PopupStoryFriendship.js
src/components/Pages/MainPage/MainPage.js
src/components/Pages/PersonalAccount/PersonalAccount.css
src/components/Pages/PersonalAccount/PersonalAccount.js
src/components/Pages/ReadAndWatch/ReadAndWatch.js
src/components/Pages/VideosPage/VideosPage.js
src/hooks/useOnClickOutside.js
src/utils/serverApiTestConfig.js

Немного переделал рендер попапов
Сделал переход с главной страницы на страницу видео и фильмы + открытие, так же сделал открытие Мейн видоса. Заменил get видео и фильмов на главной на актульную, старую закомментировал,  
Добавил для красоты видео и  трейлеры с маленьким описанием
Сделал закрытие бургера по клику outside
Сделал хук для клика outside
ну и что то по мелочи

Refactoring:  videos, moves, popups, new hook

---

src/components/Modals/PopupStoryFriendship/PopupStoryFriendship.js

Добавлен плэйсхолдер в соответствии с макетом.
Когда инпут не в фокусе, инпут заменяется на text и за счет этого отрабатывает плейсхолдер.

Placeholder Дата

---

src/components/Cards/StoryCard/StoryCard.js
src/components/UI/Button/button.css
src/components/UI/StoryImg/StoryImg.js
src/hooks/useWindowSize.js
src/utils/stories.js

Так же добавлен хук по нахождению текущего размера экрана, он работает, но пока нигде не используется.

Добавлена возможность скролить фото в историях
